// Disneyland Resort venue list for the menu price watch.
// 76 venues, verified live against the dinemenu API 2026-09-14.
// alfresco-tasting-terrace deliberately absent (Magic Key Terrace double-count).
// napa-rose-lounge left in so a 404 is reported instead of a silent drop.

const DLP = ['Disneyland Park', 'disneyland'];
const DCA = ['Disney California Adventure', 'disney-california-adventure'];
const DLH = ['Disneyland Hotel', 'disneyland-hotel'];
const GCH = ['Grand Californian Hotel', 'grand-californian-hotel'];
const PPH = ['Pixar Place Hotel', 'pixar-place-hotel'];

export const VENUES = [
  ['blue-bayou-restaurant', ...DLP],
  ['carnation-cafe', ...DLP],
  ['cafe-orleans', ...DLP],
  ['plaza-inn', ...DLP],
  ['bengal-barbecue', ...DLP],
  ['jolly-holiday-bakery-cafe', ...DLP],
  ['rancho-del-zocalo-restaurante', ...DLP],
  ['river-belle-terrace', ...DLP],
  ['docking-bay-7-food-and-cargo', ...DLP],
  ['alien-pizza-planet', ...DLP],
  ['golden-horseshoe-restaurant', ...DLP],
  ['stage-door-cafe', ...DLP],
  ['royal-street-veranda', ...DLP],
  ['mint-julep-bar', ...DLP],
  ['harbour-galley', ...DLP],
  ['tianas-palace', ...DLP],
  ['tropical-hideaway', ...DLP],
  ['tiki-juice-bar', ...DLP],
  ['market-house', ...DLP],
  ['refreshment-corner', ...DLP],
  ['gibson-girl-ice-cream-parlor', ...DLP],
  ['little-red-wagon', ...DLP],
  ['red-rose-taverne', ...DLP],
  ['maurices-treats', ...DLP],
  ['edelweiss-snacks', ...DLP],
  ['troubadour-tavern', ...DLP],
  ['galactic-grill', ...DLP],
  ['ogas-cantina', ...DLP],
  ['ronto-roasters', ...DLP],
  ['milk-stand', ...DLP],
  ['kat-sakas-kettle', ...DLP],
  ['cafe-daisy', ...DLP],
  ['good-boy-grocers', ...DLP],
  ['lamplight-lounge', ...DCA],
  ['lamplight-lounge-boardwalk-dining', ...DCA],
  ['carthay-circle-restaurant', ...DCA],
  ['flos-v8-cafe', ...DCA],
  ['pym-test-kitchen', ...DCA],
  ['pym-tasting-lab', ...DCA],
  ['smokejumpers-grill', ...DCA],
  ['paradise-garden-grill', ...DCA],
  ['magic-key-terrace', ...DCA],
  ['fiddler-fifer-and-practical-cafe', ...DCA],
  ['clarabelles-hand-scooped-ice-cream', ...DCA],
  ['mortimers-market', ...DCA],
  ['award-wieners', ...DCA],
  ['hollywood-lounge', ...DCA],
  ['studio-catering-co', ...DCA],
  ['schmoozies-smoothies', ...DCA],
  ['willies-churros', ...DCA],
  ['terran-treats', ...DCA],
  ['shawarma-palace', ...DCA],
  ['cozy-cone-motel', ...DCA],
  ['wine-country-trattoria', ...DCA],
  ['sonoma-terrace', ...DCA],
  ['ghirardelli-soda-fountain-and-chocolate-shop', ...DCA],
  ['aunt-cass-cafe', ...DCA],
  ['port-of-san-fransokyo-cerveceria', ...DCA],
  ['lucky-fortune-cookery', ...DCA],
  ['cocina-cucamonga-mexican-grill', ...DCA],
  ['boardwalk-pizza-pasta', ...DCA],
  ['jack-jack-cookie-num-nums', ...DCA],
  ['angry-dogs', ...DCA],
  ['poultry-palace', ...DCA],
  ['senor-buzz-churros', ...DCA],
  ['adorable-snowman-frosted-treats', ...DCA],
  ['corn-dog-castle', ...DCA],
  ['bayside-brews', ...DCA],
  ['trader-sams', ...DLH],
  ['tangaroa-terrace', ...DLH],
  ['palm-breeze-bar', ...DLH],
  ['craftsman-bar', ...GCH],
  ['hearthstone-lounge', ...GCH],
  ['napa-rose-lounge', ...GCH],
  ['white-water-snacks', ...GCH],
  ['sketch-pad-cafe', ...PPH],
];
